// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";

import { Tx as typeTx} from "./types"
import { TxRaw as typeTxRaw} from "./types"
import { SignDoc as typeSignDoc} from "./types"
import { SignDocDirectAux as typeSignDocDirectAux} from "./types"
import { TxBody as typeTxBody} from "./types"
import { AuthInfo as typeAuthInfo} from "./types"
import { SignerInfo as typeSignerInfo} from "./types"
import { ModeInfo as typeModeInfo} from "./types"
import { ModeInfo_Single as typeModeInfo_Single} from "./types"
import { ModeInfo_Multi as typeModeInfo_Multi} from "./types"
import { Fee as typeFee} from "./types"
import { Tip as typeTip} from "./types"
import { AuxSignerData as typeAuxSignerData} from "./types"
import {SimulateRequest} from './types/cosmos/tx/v1beta1/service'

export {  };



export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
	
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};
export default {txClient, queryClient}
